### ISSUE TITLE
Error in title

### ISSUE THREAD

**Issue by osamahamad** [Ch3rlO/api_doc#1]
The title of your repo " The sewers of Baghdad " is insulting Baghdad city with 😃 smile.

You should fix your behavior.

Fix suggestions : 

eat a dick.
remove your finger from your ass hole.

**Comment by Ch3rlO** [comment]
Your fix suggestions it's not good enough but I'll change the emoji

**Comment by Ch3rlO** [comment]
I'll reopen this issue if you have more suggestions you're more than welcome! <3

**Comment by Ch3rlO** [comment]
**Reopen for the title suggestions**

**Comment by osamahamad** [comment]
Title : The Cesspit Of Baghdad

**Comment by Ch3rlO** [comment]
Oh, I see can you make a pull request with doc.test.md file and send the test result just to make sure that nothing going to break
